-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	20 = {
		name="^3时间领主",
		playable=2,
		start="20_逃生机",
		primaries=3,
		color2=0xece47f,
		color0=0x000000,
		color1=0xece47f,
		aiflags=DODGES|METAMORPHOSIS|SOCIAL|TRACTOR_TRANSIENT|WANDER,
	},

}
