-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	ident=20,
	color=0xece47f,
	faction=20,
	count=3,
	position={0.5, 1},
	radius={0.08, 0.09},
	type=2,
	fleets={
		{20, { {0, 850000}, {1, 2000} }},
	},
	fleetCount={5, 7},
	fleetFraction=0.1,
	fortress={
		"20_时间基站",
		"20_空间基站",
		"20_C级9位_基站",
		"20_回忆25"
	},
	fortressCount={3, 6},
	fortressRadius={1200, 1400},
	unique={
		{
			"20_看不见的旋律_M",
		},
	},
	uniqueFraction=0.1,
	ambient={ 2,-1 },
	asteroidDensity={0, 0.15},
	asteroidSize={1, 16},
	asteroidFlags=PENROSE|SQUARE|HEXAGON|TRIANGLE|OCTAGON,
},
{
	ident=200,
	color=0xece47f,
	faction=20,
	count=3,
	position={0.5, 1},
	radius={0.08, 0.09},
	type=2,
	fleets={
		{20, { {0, 850000}, {1, 2000} }},
	},
	fleetCount={5, 7},
	fleetFraction=0.1,
	fortress={

	},
	fortressCount={3, 6},
	fortressRadius={1200, 1400},
	unique={
		{

		},
	},
	uniqueFraction=0.1,
	ambient={ 2,-1 },
	asteroidDensity={0, 0.15},
	asteroidSize={1, 16},
	asteroidFlags=PENROSE|SQUARE|HEXAGON|TRIANGLE|OCTAGON,
},
